package com.task_managment_api.demo.service;

import com.task_managment_api.demo.domain.entity.Task;
import com.task_managment_api.demo.dto.response.TaskResponse;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.JsonNode;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.RequiredArgsConstructor;
import lombok.Setter;
import org.springframework.stereotype.Service;
import org.springframework.ai.chat.client.ChatClient;
import org.springframework.core.ParameterizedTypeReference;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.client.RestTemplate;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.HashMap;
import java.util.Map;

@Service
public class AiTaskDescriptionService {

    private final ChatClient chatClient;
    private final OllamaClientService ollamaClientService;

    @Value("${gemini.api.key:}")
    private String geminiApiKey;

    public AiTaskDescriptionService(ChatClient.Builder chatClientBuilder, OllamaClientService ollamaClientService) {
        this.chatClient = chatClientBuilder.build();
        this.ollamaClientService = ollamaClientService;
    }

    // Helper method to query cloud Gemini API
    private String queryGemini(String prompt) {
        String apiKey = System.getProperty("gemini.api.key");
        if (apiKey == null || apiKey.isBlank()) {
            apiKey = this.geminiApiKey;
        }
        if (apiKey == null || apiKey.isBlank() || "YOUR_GEMINI_API_KEY".equals(apiKey)) {
            return null; // Fallback to local Ollama
        }

        String url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=" + apiKey;
        try {
            RestTemplate restTemplate = new RestTemplate();
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);

            Map<String, Object> textPart = new HashMap<>();
            textPart.put("text", prompt);

            Map<String, Object> partContainer = new HashMap<>();
            partContainer.put("parts", List.of(textPart));

            Map<String, Object> payload = new HashMap<>();
            payload.put("contents", List.of(partContainer));

            if (prompt.contains("JSON object") || prompt.contains("JSON array")) {
                Map<String, Object> genConfig = new HashMap<>();
                genConfig.put("responseMimeType", "application/json");
                payload.put("generationConfig", genConfig);
            }

            HttpEntity<Map<String, Object>> entity = new HttpEntity<>(payload, headers);
            ResponseEntity<String> response = restTemplate.postForEntity(url, entity, String.class);

            if (response.getStatusCode().is2xxSuccessful() && response.getBody() != null) {
                ObjectMapper mapper = new ObjectMapper();
                JsonNode root = mapper.readTree(response.getBody());
                JsonNode textNode = root.path("candidates")
                        .path(0)
                        .path("content")
                        .path("parts")
                        .path(0)
                        .path("text");
                if (!textNode.isMissingNode()) {
                    return cleanJsonResponse(textNode.asText());
                }
            }
        } catch (Exception e) {
            System.err.println("Gemini API call failed: " + e.getMessage());
        }
        return null;
    }

    // Helper method to clean markdown code blocks from LLM JSON response
    private String cleanJsonResponse(String response) {
        if (response == null) return null;
        String clean = response.trim();
        if (clean.startsWith("```")) {
            int firstLineEnd = clean.indexOf("\n");
            if (firstLineEnd != -1) {
                clean = clean.substring(firstLineEnd).trim();
            }
            if (clean.endsWith("```")) {
                clean = clean.substring(0, clean.length() - 3).trim();
            }
        }
        return clean;
    }

    // --- Feature 1: AI Task Description & Priority ---
    public AiAnalysisResult analyzeAndGenerate(String title, String currentPriority) {
        if (title == null || title.trim().isEmpty()) {
            return AiAnalysisResult.builder()
                    .description("Task description auto-generated by AI.")
                    .suggestedPriority("MEDIUM")
                    .priorityReason("Default priority for empty title.")
                    .build();
        }

        String lowerTitle = title.toLowerCase(Locale.ROOT);

        // Priority recommendation logic
        String suggestedPriority;
        String priorityReason;

        if (containsAny(lowerTitle, "urgent", "critical", "fix", "bug", "error", "crash", "security", "hata", "acil", "güvenlik", "broken", "prod")) {
            suggestedPriority = "HIGH";
            priorityReason = "Suggested HIGH: Task involves a critical bug fix, error, or security patch.";
        } else if (containsAny(lowerTitle, "ui", "style", "color", "typo", "comment", "readme", "doc", "clean", "renk", "tasarım", "doküman", "metin")) {
            suggestedPriority = "LOW";
            priorityReason = "Suggested LOW: Task is primarily a cosmetic, style, or documentation update.";
        } else {
            suggestedPriority = "MEDIUM";
            priorityReason = "Suggested MEDIUM: Standard feature development, enhancement, or integration.";
        }

        try {
            String prompt = String.format("Generate an extremely brief, concise, professional, bulleted technical description (max 2 short bullet points) in English for a task titled \"%s\". Also suggest a priority (HIGH, MEDIUM, LOW) and a short reason. Respond with a JSON object containing fields: description, suggestedPriority, priorityReason. No markdown.", title);
            
            String response = queryGemini(prompt);
            if (response != null && !response.isBlank()) {
                ObjectMapper mapper = new ObjectMapper();
                return mapper.readValue(response, AiAnalysisResult.class);
            }

            return this.chatClient.prompt(prompt)
                    .call()
                    .entity(AiAnalysisResult.class);
        } catch (Exception e) {
            // Internal fallback generator
            StringBuilder sb = new StringBuilder();
            sb.append("🤖 AI Generated Task Breakdown:\n");
            sb.append("• Perform requirement analysis and architectural breakdown for: ").append(title).append(".\n");

            if (containsAny(lowerTitle, "integration", "entegrasyon", "api", "ai")) {
                sb.append("• Design and integrate required API endpoints and data communication flow.\n");
                sb.append("• Validate payload formats, status codes, and exception handling logic.");
            } else if (containsAny(lowerTitle, "fix", "bug", "error", "hata", "düzelt")) {
                sb.append("• Investigate root cause, inspect system error logs, and reproduce issue.\n");
                sb.append("• Apply patch, verify resolution, and execute regression testing.");
            } else if (containsAny(lowerTitle, "ui", "design", "screen", "tasarım", "ekran")) {
                sb.append("• Update user interface components using modern design guidelines.\n");
                sb.append("• Verify screen responsiveness and cross-browser visual fidelity.");
            } else if (containsAny(lowerTitle, "db", "database", "sql", "veritabanı")) {
                sb.append("• Update database schema migration scripts and optimize indexing.\n");
                sb.append("• Ensure data integrity and verify query execution performance.");
            } else {
                sb.append("• Execute feature implementation and write automated unit tests.\n");
                sb.append("• Complete code review process and prepare for deployment.");
            }
            return AiAnalysisResult.builder()
                    .description(sb.toString())
                    .suggestedPriority(suggestedPriority)
                    .priorityReason(priorityReason)
                    .build();
        }
    }

    public String generateDescription(String title, String priority) {
        return analyzeAndGenerate(title, priority).getDescription();
    }

    // --- Feature 2: AI Task Generator (Prompt -> Tasks List) ---
    public List<GeneratedTaskDto> generateTasksFromPrompt(String prompt) {
        List<GeneratedTaskDto> tasks = new ArrayList<>();
        if (prompt == null || prompt.trim().isEmpty()) {
            return tasks;
        }

        try {
            String llmPrompt = String.format("Create 3 to 4 sub-tasks to achieve the goal: \"%s\". Keep titles and descriptions extremely brief (under 1 sentence each). Return ONLY a JSON array of objects with fields: title, description, priority (LOW, MEDIUM, HIGH), status (TODO, IN_PROGRESS, DONE). No markdown.", prompt);
            
            String response = queryGemini(llmPrompt);
            if (response != null && !response.isBlank()) {
                ObjectMapper mapper = new ObjectMapper();
                return mapper.readValue(response, new TypeReference<List<GeneratedTaskDto>>() {});
            }

            return this.chatClient.prompt(llmPrompt)
                    .call()
                    .entity(new ParameterizedTypeReference<List<GeneratedTaskDto>>() {});
        } catch (Exception e) {
            // Fall back to hardcoded list if Ollama fails or returns invalid format
        }

        String lowerPrompt = prompt.toLowerCase(Locale.ROOT);

        // Generate 3 to 4 structured sub-tasks based on prompt context (Fallback)
        if (containsAny(lowerPrompt, "auth", "login", "security", "giriş", "şifre")) {
            tasks.add(new GeneratedTaskDto("Implement OAuth2 & JWT Authentication Flow", "Design secure token validation and refresh token mechanics.", "HIGH", "TODO"));
            tasks.add(new GeneratedTaskDto("Build Login & Register Frontend Forms", "Create responsive React forms with form validation and remember-me persistence.", "MEDIUM", "TODO"));
            tasks.add(new GeneratedTaskDto("Configure CORS & Rate Limiting", "Set up Spring Security CORS configuration and API rate limit protection.", "HIGH", "TODO"));
            tasks.add(new GeneratedTaskDto("Write Auth Unit & Integration Tests", "Execute security unit testing for login, token expiry, and password hashing.", "MEDIUM", "TODO"));
        } else if (containsAny(lowerPrompt, "shop", "cart", "pay", "order", "e-commerce", "ödeme")) {
            tasks.add(new GeneratedTaskDto("Build Product Catalog & Filter API", "Develop REST API endpoints for product searching, sorting, and pagination.", "HIGH", "TODO"));
            tasks.add(new GeneratedTaskDto("Implement Shopping Cart & Session Storage", "Create frontend cart state management and persistent local storage sync.", "MEDIUM", "TODO"));
            tasks.add(new GeneratedTaskDto("Integrate Payment Gateway Gateway API", "Integrate Stripe/PayPal gateway, handling webhooks and checkout success.", "HIGH", "TODO"));
            tasks.add(new GeneratedTaskDto("Design Order Summary & Email Receipt Flow", "Build order confirmation UI and automated transaction confirmation emails.", "LOW", "TODO"));
        } else {
            tasks.add(new GeneratedTaskDto("System Requirements & API Architecture for: " + prompt, "Define data models, REST endpoints, and architectural requirements.", "HIGH", "TODO"));
            tasks.add(new GeneratedTaskDto("Develop Core Service & Controller Endpoints", "Implement Spring Boot business logic, validation, and JPA repositories.", "HIGH", "TODO"));
            tasks.add(new GeneratedTaskDto("Build Responsive Frontend Components", "Construct interactive UI components with modern styling and state management.", "MEDIUM", "TODO"));
            tasks.add(new GeneratedTaskDto("Execute QA Testing & Code Review", "Run unit tests, end-to-end integration verification, and deployment prep.", "LOW", "TODO"));
        }

        return tasks;
    }

    // --- Feature 3: AI Executive Analytics & Status Reports ---
    public AiReportDto generateExecutiveReport(List<TaskResponse> userTasks) {
        int total = userTasks.size();
        int todoCount = 0;
        int inProgressCount = 0;
        int doneCount = 0;
        int highPriorityCount = 0;

        for (TaskResponse t : userTasks) {
            String status = t.getStatus() != null ? t.getStatus().name() : "TODO";
            String priority = t.getPriority() != null ? t.getPriority().name() : "MEDIUM";

            if ("DONE".equals(status)) doneCount++;
            else if ("IN_PROGRESS".equals(status)) inProgressCount++;
            else todoCount++;

            if ("HIGH".equals(priority)) highPriorityCount++;
        }

        double completionRate = total > 0 ? (doneCount * 100.0 / total) : 0.0;

        String summaryPrompt = String.format("Summarize the project status in three extremely short bullet points (max 1 sentence each). Total tasks: %d, DONE: %d, IN_PROGRESS: %d, TODO: %d, HIGH priority: %d.", total, doneCount, inProgressCount, todoCount, highPriorityCount);
        
        String summary = queryGemini(summaryPrompt);
        if (summary == null || summary.isBlank()) {
            summary = this.chatClient.prompt(summaryPrompt)
                    .call()
                    .content();
        }
        if (summary == null || summary.isBlank()) {
            summary = String.format("📊 Project Status Overview:\n• Completion Rate: %.1f%% (%d of %d tasks completed).\n• Active Workload: %d tasks currently in progress, %d pending in queue.\n• Critical Focus: %d High Priority tasks require active monitoring.",
                    completionRate, doneCount, total, inProgressCount, todoCount, highPriorityCount);
        }

        List<String> recommendations = new ArrayList<>();
        if (highPriorityCount > (total / 2) && total > 0) {
            recommendations.add("⚠️ High priority backlog exceeds 50%. Consider re-assessing task urgencies or allocating extra engineering resources.");
        }
        if (inProgressCount > 5) {
            recommendations.add("⚠️ High Work-In-Progress (WIP). Limit in-progress tasks to 3-5 items to improve sprint velocity.");
        }
        if (completionRate >= 50.0) {
            recommendations.add("🎉 Strong progress! Over half of the total project tasks are completed.");
        } else {
            recommendations.add("💡 Focus on completing in-progress items before picking up new items from the To Do queue.");
        }

        return AiReportDto.builder()
                .totalTasks(total)
                .todoCount(todoCount)
                .inProgressCount(inProgressCount)
                .doneCount(doneCount)
                .highPriorityCount(highPriorityCount)
                .completionRatePercentage(Math.round(completionRate * 10.0) / 10.0)
                .executiveSummary(summary)
                .recommendations(recommendations)
                .build();
    }

    private boolean containsAny(String text, String... keywords) {
        for (String kw : keywords) {
            if (text.contains(kw)) {
                return true;
            }
        }
        return false;
    }

    @Getter
    @Setter
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class AiAnalysisResult {
        private String description;
        private String suggestedPriority;
        private String priorityReason;
    }

    @Getter
    @Setter
    @AllArgsConstructor
    @NoArgsConstructor
    public static class GeneratedTaskDto {
        private String title;
        private String description;
        private String priority;
        private String status;
    }

    @Getter
    @Setter
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class AiReportDto {
        private int totalTasks;
        private int todoCount;
        private int inProgressCount;
        private int doneCount;
        private int highPriorityCount;
        private double completionRatePercentage;
        private String executiveSummary;
        private List<String> recommendations;
    }
}
